name: 🐛 Bug Report
description: Report a bug or unexpected behavior in My Sailing Log
title: "[Bug]: "
labels: ["bug", "needs-triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to report a bug! Please provide as much detail as possible to help us understand and fix the issue.
        
        **Before submitting:**
        - Check if this bug has already been reported
        - Make sure you're using the latest version
        - Try refreshing the page or clearing your browser cache

  - type: input
    id: browser
    attributes:
      label: Browser
      description: Which browser are you using?
      placeholder: "e.g., Chrome 120, Firefox 119, Safari 17"
    validations:
      required: true

  - type: input
    id: device
    attributes:
      label: Device/Operating System
      description: What device and OS are you using?
      placeholder: "e.g., Windows 11, macOS 14, iPhone 15, Android 13"
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Tell us what you were doing when the bug occurred
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What should have happened?
      placeholder: "Describe what you expected to happen"
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: "Describe what actually happened, including any error messages"
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain the problem
      placeholder: "Drag and drop images here or paste image URLs"

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other information that might be helpful?
      placeholder: "Add any other context about the problem here"

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to our Code of Conduct
      options:
        - label: I have searched for similar issues and this is not a duplicate
          required: true
        - label: I have read the Code of Conduct and agree to follow it
          required: true